import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";

import Container from "@mui/material/Container";
import Drawer from "@/components/UI/Drawer/Drawer";
import FooterBanner from "@/components/UI/FooterBanner/FooterBanner";
import { useCallback, useState } from "react";

import dynamic from "next/dynamic";
import { Data, MarkerData } from "../mocks/types";
import { useMapActions } from "@/stores/mapStore";

const LeafletMap = dynamic(() => import("@/components/UI/Map"), {
  ssr: false,
});

export default function Home({ results }: { results: MarkerData[] }) {
  const { toggleDrawer, setDrawerData } = useMapActions();

  const handleMarkerClick = useCallback(
    (
      event: React.KeyboardEvent | React.MouseEvent,
      markerData?: MarkerData
    ) => {
      if (
        event.type === "keydown" &&
        ((event as React.KeyboardEvent).key === "Tab" ||
          (event as React.KeyboardEvent).key === "Shift")
      )
        return;

      toggleDrawer();

      if (markerData) {
        setDrawerData(markerData);
      }
    },
    []
  );

  return (
    <>
      <Head>
        <title>Afet Haritası | Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxWidth={false} disableGutters>
          <LeafletMap onClickMarker={handleMarkerClick} data={results} />
        </Container>
        <Drawer toggler={handleMarkerClick} />
        <FooterBanner />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Server-side requests are mocked by `mocks/server.ts`.
  const res = await fetch(
    "https://public-sdc.trendyol.com/discovery-web-websfxgeolocation-santral/geocode?address=gaziantep"
  );
  const data = (await res.json()) as Data;
  const results = data.results;

  return {
    props: {
      results,
    },
  };
}
